package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * Country generated by hbm2java
 */

@Embeddable
public class Country implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private Integer countryId;
	private String countryName;
	
	private List<Useraccount> useraccounts = new ArrayList(0);
	
	private List<Countryadmin> countryadmins = new ArrayList(0);
	
	//private Set useraccounts = new HashSet(0);
	//private Set countryadmins = new HashSet(0);

	public Country() {
	}

	public Country(String countryName) {
		this.countryName = countryName;
	}

	public Country(String countryName, List useraccounts, List countryadmins) {
		this.countryName = countryName;
		this.useraccounts = useraccounts;
		this.countryadmins = countryadmins;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public List<Useraccount> getUseraccounts() {
		return this.useraccounts;
	}

	public void setUseraccounts(List<Useraccount>  useraccounts) {
		this.useraccounts = useraccounts;
	}

	public List<Countryadmin>  getCountryadmins() {
		return this.countryadmins;
	}

	public void setCountryadmins(List<Countryadmin>  countryadmins) {
		this.countryadmins = countryadmins;
	}

}
