package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import java.util.Date;

import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ear generated by hbm2java
 */
@Embeddable
public class Ear implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private Integer cornId;
	@JsonIgnore
	private Plot plot;
	@JsonIgnore
	private Ratelevel ratelevelByDerRateM;
	@JsonIgnore
	private Ratelevel ratelevelByDerRateA;
	private String earImgPath;
	private String earImgPathS;
	private float derPercentA;
	private Float derPercentM;
	private Integer imgPosX;
	private Integer imgPosY;
	private Integer imgWidth;
	private Integer imgHeigh;
	private String cornDetectType;
	private String earProgress;
	private Date lastUpdate;

	public Ear() {
	}

	public Ear(Plot plot, String earImgPath, String earImgPathS, float derPercentA, String cornDetectType,
			String earProgress, Date lastUpdate) {
		this.plot = plot;
		this.earImgPath = earImgPath;
		this.earImgPathS = earImgPathS;
		this.derPercentA = derPercentA;
		this.cornDetectType = cornDetectType;
		this.earProgress = earProgress;
		this.lastUpdate = lastUpdate;
	}

	public Ear(Plot plot, Ratelevel ratelevelByDerRateM, Ratelevel ratelevelByDerRateA, String earImgPath,
			String earImgPathS, float derPercentA, Float derPercentM, Integer imgPosX, Integer imgPosY,
			Integer imgWidth, Integer imgHeigh, String cornDetectType, String earProgress, Date lastUpdate) {
		this.plot = plot;
		this.ratelevelByDerRateM = ratelevelByDerRateM;
		this.ratelevelByDerRateA = ratelevelByDerRateA;
		this.earImgPath = earImgPath;
		this.earImgPathS = earImgPathS;
		this.derPercentA = derPercentA;
		this.derPercentM = derPercentM;
		this.imgPosX = imgPosX;
		this.imgPosY = imgPosY;
		this.imgWidth = imgWidth;
		this.imgHeigh = imgHeigh;
		this.cornDetectType = cornDetectType;
		this.earProgress = earProgress;
		this.lastUpdate = lastUpdate;
	}

	public Integer getCornId() {
		return this.cornId;
	}

	public void setCornId(Integer cornId) {
		this.cornId = cornId;
	}

	public Plot getPlot() {
		return this.plot;
	}

	public void setPlot(Plot plot) {
		this.plot = plot;
	}

	public Ratelevel getRatelevelByDerRateM() {
		return this.ratelevelByDerRateM;
	}

	public void setRatelevelByDerRateM(Ratelevel ratelevelByDerRateM) {
		this.ratelevelByDerRateM = ratelevelByDerRateM;
	}

	public Ratelevel getRatelevelByDerRateA() {
		return this.ratelevelByDerRateA;
	}

	public void setRatelevelByDerRateA(Ratelevel ratelevelByDerRateA) {
		this.ratelevelByDerRateA = ratelevelByDerRateA;
	}

	public String getEarImgPath() {
		return this.earImgPath;
	}

	public void setEarImgPath(String earImgPath) {
		this.earImgPath = earImgPath;
	}

	public String getEarImgPathS() {
		return this.earImgPathS;
	}

	public void setEarImgPathS(String earImgPathS) {
		this.earImgPathS = earImgPathS;
	}

	public float getDerPercentA() {
		return this.derPercentA;
	}

	public void setDerPercentA(float derPercentA) {
		this.derPercentA = derPercentA;
	}

	public Float getDerPercentM() {
		return this.derPercentM;
	}

	public void setDerPercentM(Float derPercentM) {
		this.derPercentM = derPercentM;
	}

	public Integer getImgPosX() {
		return this.imgPosX;
	}

	public void setImgPosX(Integer imgPosX) {
		this.imgPosX = imgPosX;
	}

	public Integer getImgPosY() {
		return this.imgPosY;
	}

	public void setImgPosY(Integer imgPosY) {
		this.imgPosY = imgPosY;
	}

	public Integer getImgWidth() {
		return this.imgWidth;
	}

	public void setImgWidth(Integer imgWidth) {
		this.imgWidth = imgWidth;
	}

	public Integer getImgHeigh() {
		return this.imgHeigh;
	}

	public void setImgHeigh(Integer imgHeigh) {
		this.imgHeigh = imgHeigh;
	}

	public String getCornDetectType() {
		return this.cornDetectType;
	}

	public void setCornDetectType(String cornDetectType) {
		this.cornDetectType = cornDetectType;
	}

	public String getEarProgress() {
		return this.earProgress;
	}

	public void setEarProgress(String earProgress) {
		this.earProgress = earProgress;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
