package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Embeddable;

/**
 * Ratelevel generated by hbm2java
 */
@Embeddable
public class Ratelevel implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private Integer rateId;
	private String level;
	private String description;
	private int minPercent;
	private int maxPercent;
	private float weight;
	private int computable;
	
	private List<Ear> earsForDerRateM = new ArrayList(0);
	private List<Ear> earsForDerRateA = new ArrayList(0);
	private List<Undetectear> undetectears = new ArrayList(0);

	//private Set earsForDerRateM = new HashSet(0);
	//private Set earsForDerRateA = new HashSet(0);
	//private Set undetectears = new HashSet(0);

	public Ratelevel() {
	}

	public Ratelevel(String level, String description, int minPercent, int maxPercent, float weight, int computable) {
		this.level = level;
		this.description = description;
		this.minPercent = minPercent;
		this.maxPercent = maxPercent;
		this.weight = weight;
		this.computable = computable;
	}

	public Ratelevel(String level, String description, int minPercent, int maxPercent, float weight, int computable,
			List earsForDerRateM, List earsForDerRateA, List undetectears) {
		this.level = level;
		this.description = description;
		this.minPercent = minPercent;
		this.maxPercent = maxPercent;
		this.weight = weight;
		this.computable = computable;
		this.earsForDerRateM = earsForDerRateM;
		this.earsForDerRateA = earsForDerRateA;
		this.undetectears = undetectears;
	}

	public Integer getRateId() {
		return this.rateId;
	}

	public void setRateId(Integer rateId) {
		this.rateId = rateId;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getMinPercent() {
		return this.minPercent;
	}

	public void setMinPercent(int minPercent) {
		this.minPercent = minPercent;
	}

	public int getMaxPercent() {
		return this.maxPercent;
	}

	public void setMaxPercent(int maxPercent) {
		this.maxPercent = maxPercent;
	}

	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public int getComputable() {
		return this.computable;
	}

	public void setComputable(int computable) {
		this.computable = computable;
	}

	public List<Ear> getEarsForDerRateM() {
		return this.earsForDerRateM;
	}

	public void setEarsForDerRateM(List<Ear> earsForDerRateM) {
		this.earsForDerRateM = earsForDerRateM;
	}

	public List<Ear> getEarsForDerRateA() {
		return this.earsForDerRateA;
	}

	public void setEarsForDerRateA(List<Ear> earsForDerRateA) {
		this.earsForDerRateA = earsForDerRateA;
	}

	public List<Undetectear> getUndetectears() {
		return this.undetectears;
	}

	public void setUndetectears(List<Undetectear> undetectears) {
		this.undetectears = undetectears;
	}

}
