package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Trial generated by hbm2java
 */
@Embeddable
public class Trial implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private String trialId;
	@JsonIgnore
	private Useraccount useraccount;
	private String aliasName;
	private String trialActive;
	private String trialStatus;
	private int plotSettingAutoLockUpload;
	private int plotSettingAutoLockApproved;
	private Date createDate;
	private Date lastUpdate;
	
	//private Set usertrials = new HashSet(0);
	
	//private Set plots = new HashSet(0);
	private List plots = new ArrayList();
	private List usertrials = new ArrayList(0);

	public Trial() {
	}

	public Trial(String trialId, Useraccount useraccount, String trialActive, String trialStatus,
			int plotSettingAutoLockUpload, int plotSettingAutoLockApproved, Date createDate, Date lastUpdate) {
		this.trialId = trialId;
		this.useraccount = useraccount;
		this.trialActive = trialActive;
		this.trialStatus = trialStatus;
		this.plotSettingAutoLockUpload = plotSettingAutoLockUpload;
		this.plotSettingAutoLockApproved = plotSettingAutoLockApproved;
		this.createDate = createDate;
		this.lastUpdate = lastUpdate;
	}

	public Trial(String trialId, Useraccount useraccount, String aliasName, String trialActive, String trialStatus,
			int plotSettingAutoLockUpload, int plotSettingAutoLockApproved, Date createDate, Date lastUpdate,
			List usertrials, List plots) {
		this.trialId = trialId;
		this.useraccount = useraccount;
		this.aliasName = aliasName;
		this.trialActive = trialActive;
		this.trialStatus = trialStatus;
		this.plotSettingAutoLockUpload = plotSettingAutoLockUpload;
		this.plotSettingAutoLockApproved = plotSettingAutoLockApproved;
		this.createDate = createDate;
		this.lastUpdate = lastUpdate;
		this.usertrials = usertrials;
		this.plots = plots;
	}

	public String getTrialId() {
		return this.trialId;
	}

	public void setTrialId(String trialId) {
		this.trialId = trialId;
	}

	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	public String getAliasName() {
		return this.aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public String getTrialActive() {
		return this.trialActive;
	}

	public void setTrialActive(String trialActive) {
		this.trialActive = trialActive;
	}

	public String getTrialStatus() {
		return this.trialStatus;
	}

	public void setTrialStatus(String trialStatus) {
		this.trialStatus = trialStatus;
	}

	public int getPlotSettingAutoLockUpload() {
		return this.plotSettingAutoLockUpload;
	}

	public void setPlotSettingAutoLockUpload(int plotSettingAutoLockUpload) {
		this.plotSettingAutoLockUpload = plotSettingAutoLockUpload;
	}

	public int getPlotSettingAutoLockApproved() {
		return this.plotSettingAutoLockApproved;
	}

	public void setPlotSettingAutoLockApproved(int plotSettingAutoLockApproved) {
		this.plotSettingAutoLockApproved = plotSettingAutoLockApproved;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public List<Usertrial> getUsertrials() {
		return this.usertrials;
	}

	public void setUsertrials(List<Usertrial> usertrials) {
		this.usertrials = usertrials;
	}

	public List<Plot> getPlots() {
		return this.plots;
	}

	public void setPlots(List<Plot> plots) {
		this.plots = plots;
	}	

}
