package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Undetectear generated by hbm2java
 */
@Embeddable
public class Undetectear implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private Integer undetectEarId;
	@JsonIgnore
	private Plot plot;
	@JsonIgnore
	private Ratelevel ratelevel;
	private String note;
	private String missingEarImgPath;

	public Undetectear() {
	}

	public Undetectear(Plot plot, Ratelevel ratelevel, String note) {
		this.plot = plot;
		this.ratelevel = ratelevel;
		this.note = note;
	}

	public Undetectear(Plot plot, Ratelevel ratelevel, String note, String missingEarImgPath) {
		this.plot = plot;
		this.ratelevel = ratelevel;
		this.note = note;
		this.missingEarImgPath = missingEarImgPath;
	}

	public Integer getUndetectEarId() {
		return this.undetectEarId;
	}

	public void setUndetectEarId(Integer undetectEarId) {
		this.undetectEarId = undetectEarId;
	}

	public Plot getPlot() {
		return this.plot;
	}

	public void setPlot(Plot plot) {
		this.plot = plot;
	}

	public Ratelevel getRatelevel() {
		return this.ratelevel;
	}

	public void setRatelevel(Ratelevel ratelevel) {
		this.ratelevel = ratelevel;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getMissingEarImgPath() {
		return this.missingEarImgPath;
	}

	public void setMissingEarImgPath(String missingEarImgPath) {
		this.missingEarImgPath = missingEarImgPath;
	}

}
