package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Useraccount generated by hbm2java
 */
@Embeddable
public class Useraccount implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private Integer userId;
	@JsonIgnore
	private Country country;
	@JsonIgnore
	private Position position;
	@JsonIgnore
	private String userName;
	private String firstName;
	private String lastName;
	@JsonIgnore
	private String password;
	private String picture;
	private String adminRole;
	private Date createDate;
	private Date lastAccess;
	private String userStatus;
	@JsonIgnore
	private String token;
	private Date tokenDateTime;
	/*
	private Set plotsForApproveBy = new HashSet(0);
	private Set usertrials = new HashSet(0);
	private Set countryadmins = new HashSet(0);
	private Set trials = new HashSet(0);
	private Set plotsForUploadBy = new HashSet(0);
	*/
	private List plotsForApproveBy = new ArrayList<Plot>(0);
	private List usertrials =new ArrayList<Usertrial>(0);
	private List countryadmins = new ArrayList<Countryadmin>(0);
	private List trials = new ArrayList<Trial>(0);
	private List plotsForUploadBy = new ArrayList<Plot>(0);
	
	

	public Useraccount() {
	}

	public Useraccount(Country country, Position position, String userName, String firstName, String lastName,
			String password, String adminRole, Date createDate, Date lastAccess, String userStatus) {
		this.country = country;
		this.position = position;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.adminRole = adminRole;
		this.createDate = createDate;
		this.lastAccess = lastAccess;
		this.userStatus = userStatus;
	}

	/*public Useraccount(Country country, Position position, String userName, String firstName, String lastName,
			String password, String picture, String adminRole, Date createDate, Date lastAccess, String userStatus,
			String token, Date tokenDateTime, Set plotsForApproveBy, Set usertrials, Set countryadmins, Set trials,
			Set plotsForUploadBy) {
		this.country = country;
		this.position = position;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.picture = picture;
		this.adminRole = adminRole;
		this.createDate = createDate;
		this.lastAccess = lastAccess;
		this.userStatus = userStatus;
		this.token = token;
		this.tokenDateTime = tokenDateTime;
		this.plotsForApproveBy = plotsForApproveBy;
		this.usertrials = usertrials;
		this.countryadmins = countryadmins;
		this.trials = trials;
		this.plotsForUploadBy = plotsForUploadBy;
	}*/

	public Useraccount(Country country, Position position, String userName, String firstName, String lastName,
			String password, String picture, String adminRole, Date createDate, Date lastAccess, String userStatus,
			String token, Date tokenDateTime, List plotsForApproveBy, List usertrials, List countryadmins, List trials,
			List plotsForUploadBy) {
		this.country = country;
		this.position = position;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.picture = picture;
		this.adminRole = adminRole;
		this.createDate = createDate;
		this.lastAccess = lastAccess;
		this.userStatus = userStatus;
		this.token = token;
		this.tokenDateTime = tokenDateTime;
		this.plotsForApproveBy = plotsForApproveBy;
		this.usertrials = usertrials;
		this.countryadmins = countryadmins;
		this.trials = trials;
		this.plotsForUploadBy = plotsForUploadBy;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getAdminRole() {
		return this.adminRole;
	}

	public void setAdminRole(String adminRole) {
		this.adminRole = adminRole;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastAccess() {
		return this.lastAccess;
	}

	public void setLastAccess(Date lastAccess) {
		this.lastAccess = lastAccess;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getTokenDateTime() {
		return this.tokenDateTime;
	}

	public void setTokenDateTime(Date tokenDateTime) {
		this.tokenDateTime = tokenDateTime;
	}

	/*public Set getPlotsForApproveBy() {
		return this.plotsForApproveBy;
	}

	public void setPlotsForApproveBy(Set plotsForApproveBy) {
		this.plotsForApproveBy = plotsForApproveBy;
	}

	public Set getUsertrials() {
		return this.usertrials;
	}

	public void setUsertrials(Set usertrials) {
		this.usertrials = usertrials;
	}

	public Set getCountryadmins() {
		return this.countryadmins;
	}

	public void setCountryadmins(Set countryadmins) {
		this.countryadmins = countryadmins;
	}

	public Set getTrials() {
		return this.trials;
	}

	public void setTrials(Set trials) {
		this.trials = trials;
	}

	public Set getPlotsForUploadBy() {
		return this.plotsForUploadBy;
	}

	public void setPlotsForUploadBy(Set plotsForUploadBy) {
		this.plotsForUploadBy = plotsForUploadBy;
	}
	*/
	
	public String toString() {
	    return "[UserAccount ,firstName:" +  firstName + " lastName:"+lastName+" ]";
	}

	public List<Plot> getPlotsForApproveBy() {
		return plotsForApproveBy;
	}

	public void setPlotsForApproveBy(List<Plot> plotsForApproveBy) {
		this.plotsForApproveBy = plotsForApproveBy;
	}

	public List<Usertrial> getUsertrials() {
		return usertrials;
	}

	public void setUsertrials(List<Usertrial> usertrials) {
		this.usertrials = usertrials;
	}

	public List<Countryadmin> getCountryadmins() {
		return countryadmins;
	}

	public void setCountryadmins(List<Countryadmin> countryadmins) {
		this.countryadmins = countryadmins;
	}

	public List<Trial> getTrials() {
		return trials;
	}

	public void setTrials(List<Trial>  trials) {
		this.trials = trials;
	}

	public List<Plot> getPlotsForUploadBy() {
		return plotsForUploadBy;
	}

	public void setPlotsForUploadBy(List<Plot> plotsForUploadBy) {
		this.plotsForUploadBy = plotsForUploadBy;
	}

}
