package syngenta.der.entities;
// Generated Oct 14, 2021, 2:35:26 PM by Hibernate Tools 5.5.3.Final

import javax.persistence.Embeddable;

/**
 * UsertrialId generated by hbm2java
 */
@Embeddable
public class UsertrialId implements java.io.Serializable {

	private static final long serialVersionUID = -7415410969017941320L;
	private int userId;
	private String trialId;

	public UsertrialId() {
	}

	public UsertrialId(int userId, String trialId) {
		this.userId = userId;
		this.trialId = trialId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getTrialId() {
		return this.trialId;
	}

	public void setTrialId(String trialId) {
		this.trialId = trialId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsertrialId))
			return false;
		UsertrialId castOther = (UsertrialId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getTrialId() == castOther.getTrialId()) || (this.getTrialId() != null
						&& castOther.getTrialId() != null && this.getTrialId().equals(castOther.getTrialId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getTrialId() == null ? 0 : this.getTrialId().hashCode());
		return result;
	}

}
